# Checkout
checkout_secure_checkout:
    pattern:  /secure-checkout.html
    defaults: { _controller: WebIlluminationShopBundle:Checkout:index }
    requirements:
        _scheme:  https
checkout_ajax_check_email_address:
    pattern:  /checkout/ajaxCheckEmailAddress
    defaults: { _controller: WebIlluminationShopBundle:Checkout:ajaxCheckEmailAddress }
checkout_ajax_create_user:
    pattern:  /checkout/ajaxCreateUser
    defaults: { _controller: WebIlluminationShopBundle:Checkout:ajaxCreateUser }
checkout_ajax_save_order:
    pattern:  /checkout/ajaxSaveOrder
    defaults: { _controller: WebIlluminationShopBundle:Checkout:ajaxSaveOrder }
checkout_ajax_get_order_information:
    pattern:  /checkout/ajaxGetOrderInformation
    defaults: { _controller: WebIlluminationShopBundle:Checkout:ajaxGetOrderInformation }
checkout_ajax_get_delivery_options:
    pattern:  /checkout/ajaxGetDeliveryOptions
    defaults: { _controller: WebIlluminationShopBundle:Checkout:ajaxGetDeliveryOptions }
checkout_ajax_add_notes:
    pattern:  /checkout/ajaxAddNotes
    defaults: { _controller: WebIlluminationShopBundle:Checkout:ajaxAddNotes }
checkout_order_placed:
    pattern:  /{paymentType}/order-placed.html
    defaults: { _controller: WebIlluminationShopBundle:Checkout:orderPlaced }
    requirements:
        _scheme:  https
checkout_order_failed:
    pattern:  /{paymentType}/order-failed.html
    defaults: { _controller: WebIlluminationShopBundle:Checkout:orderFailed }
    requirements:
        _scheme:  https
    
# Basket
basket_your_basket:
    pattern:  /your-basket.html
    defaults: { _controller: WebIlluminationShopBundle:Basket:index }
    requirements:
        _scheme:  https
basket_ajax_get_basket_summary:
    pattern:  /basket/ajaxGetBasketSummary
    defaults: { _controller: WebIlluminationShopBundle:Basket:ajaxGetBasketSummary }
basket_ajax_get_basket_contents:
    pattern:  /basket/ajaxGetBasketContents
    defaults: { _controller: WebIlluminationShopBundle:Basket:ajaxGetBasketContents }
basket_ajax_get_basket_totals:
    pattern:  /basket/ajaxGetBasketTotals
    defaults: { _controller: WebIlluminationShopBundle:Basket:ajaxGetBasketTotals }
basket_ajax_get_membership_card_discount:
    pattern:  /basket/ajaxGetMembershipCardDiscount
    defaults: { _controller: WebIlluminationShopBundle:Basket:ajaxGetMembershipCardDiscount }
basket_ajax_get_basket_delivery_options:
    pattern:  /basket/ajaxGetBasketDeliveryOptions
    defaults: { _controller: WebIlluminationShopBundle:Basket:ajaxGetBasketDeliveryOptions }
basket_ajax_update_delivery_options:
    pattern:  /basket/ajaxUpdateDeliveryOptions
    defaults: { _controller: WebIlluminationShopBundle:Basket:ajaxUpdateDeliveryOptions }
basket_ajax_add_to_basket:
    pattern:  /basket/ajaxAddToBasket
    defaults: { _controller: WebIlluminationShopBundle:Basket:ajaxAddToBasket }
basket_ajax_add_non_product_to_basket:
    pattern:  /basket/ajaxAddNonProductToBasket
    defaults: { _controller: WebIlluminationShopBundle:Basket:ajaxAddNonProductToBasket }
basket_ajax_update_basket_item:
    pattern:  /basket/ajaxUpdateBasketItem
    defaults: { _controller: WebIlluminationShopBundle:Basket:ajaxUpdateBasketItem }
basket_ajax_delete_basket_item:
    pattern:  /basket/ajaxDeleteBasketItem
    defaults: { _controller: WebIlluminationShopBundle:Basket:ajaxDeleteBasketItem }
basket_ajax_clear_basket:
    pattern:  /basket/ajaxClearBasket
    defaults: { _controller: WebIlluminationShopBundle:Basket:ajaxClearBasket }
basket_ajax_add_membership_card_to_basket:
    pattern:  /basket/ajaxAddMembershipCardToBasket
    defaults: { _controller: WebIlluminationShopBundle:Basket:ajaxAddMembershipCardToBasket }
basket_ajax_delete_membership_card:
    pattern:  /basket/ajaxDeleteMembershipCard
    defaults: { _controller: WebIlluminationShopBundle:Basket:ajaxDeleteMembershipCard }
basket_ajax_redeem_membership_card_number:
    pattern:  /basket/ajaxRedeemMembershipCardNumber
    defaults: { _controller: WebIlluminationShopBundle:Basket:ajaxRedeemMembershipCardNumber }
basket_ajax_redeem_voucher_code:
    pattern:  /basket/ajaxRedeemVoucherCode
    defaults: { _controller: WebIlluminationShopBundle:Basket:ajaxRedeemVoucherCode }
basket_ajax_make_donation:
    pattern:  /basket/ajaxMakeDonation
    defaults: { _controller: WebIlluminationShopBundle:Basket:ajaxMakeDonation }
basket_ajax_delete_membership_card_number:
    pattern:  /basket/ajaxDeleteMembershipCardNumber
    defaults: { _controller: WebIlluminationShopBundle:Basket:ajaxDeleteMembershipCardNumber }
basket_ajax_delete_voucher_code:
    pattern:  /basket/ajaxDeleteVoucherCode
    defaults: { _controller: WebIlluminationShopBundle:Basket:ajaxDeleteVoucherCode }