parameters:
    web_illumination_admin.brand_service.class: WebIllumination\AdminBundle\Services\BrandService
    web_illumination_admin.department_service.class: WebIllumination\AdminBundle\Services\DepartmentService
    web_illumination_admin.product_service.class: WebIllumination\AdminBundle\Services\ProductService
    web_illumination_admin.contact_service.class: WebIllumination\AdminBundle\Services\ContactService
    web_illumination_admin.google_service.class: WebIllumination\AdminBundle\Services\GoogleService
    web_illumination_admin.image_service.class: WebIllumination\AdminBundle\Services\ImageService
    web_illumination_admin.seo_service.class: WebIllumination\AdminBundle\Services\SeoService
    web_illumination_admin.setting_service.class: WebIllumination\AdminBundle\Services\SettingService
    web_illumination_admin.basket_service.class: WebIllumination\AdminBundle\Services\BasketService
    web_illumination_admin.order_service.class: WebIllumination\AdminBundle\Services\OrderService
    web_illumination_admin.system_service.class: WebIllumination\AdminBundle\Services\SystemService
    web_illumination_admin.sage_pay_service.class: WebIllumination\AdminBundle\Services\SagePayService
    web_illumination_admin.pay_pal_service.class: WebIllumination\AdminBundle\Services\PayPalService

services:
    web_illumination_admin.brand_service:
        class: %web_illumination_admin.brand_service.class%
        arguments: [@service_container]
    web_illumination_admin.department_service:
        class: %web_illumination_admin.department_service.class%
        arguments: [@service_container]
    web_illumination_admin.product_service:
        class: %web_illumination_admin.product_service.class%
        arguments: [@service_container]
    web_illumination_admin.contact_service:
        class: %web_illumination_admin.contact_service.class%
        arguments: [@service_container]
    web_illumination_admin.google_service:
        class: %web_illumination_admin.google_service.class%
        arguments: [@service_container]
    web_illumination_admin.image_service:
        class: %web_illumination_admin.image_service.class%
        arguments: [@service_container]
    web_illumination_admin.seo_service:
        class: %web_illumination_admin.seo_service.class%
        arguments: [@service_container]
    web_illumination_admin.basket_service:
        class: %web_illumination_admin.basket_service.class%
        arguments: [@service_container]
    web_illumination_admin.order_service:
        class: %web_illumination_admin.order_service.class%
        arguments: [@service_container]
    web_illumination_admin.system_service:
        class: %web_illumination_admin.system_service.class%
        arguments: [@service_container]
    web_illumination_admin.sage_pay_service:
        class: %web_illumination_admin.sage_pay_service.class%
        arguments: [@service_container]
    web_illumination_admin.pay_pal_service:
        class: %web_illumination_admin.pay_pal_service.class%
        arguments: [@service_container]
    web_illumination_admin.setting_service:
        class: %web_illumination_admin.setting_service.class%
        arguments: [@service_container]
