services:
  # Twig Extensions
  web_illumination_site.twig.currency_extension:
    class: WebIllumination\SiteBundle\Twig\CurrencyExtension
    tags:
      - { name: twig.extension }

  # Managers
  web_illumination_site.manager.product:
    class: WebIllumination\SiteBundle\Manager\ProductManager
    arguments: [@doctrine, @web_illumination_site.manager.seo]
  web_illumination_site.manager.image:
    class: WebIllumination\SiteBundle\Manager\ImageManager
    arguments: [@doctrine]
  web_illumination_site.manager.seo:
    class: WebIllumination\SiteBundle\Manager\SeoManager
    arguments: [@doctrine]

  # Indexers
  web_illumination_site.indexer.product:
    class: WebIllumination\SiteBundle\Indexer\ProductIndexer
    arguments: [@solarium.client.product, @doctrine]

  # Listeners
  web_illumination_site.listener.product:
      class: WebIllumination\SiteBundle\EventListener\ProductListener
      arguments: [@web_illumination_site.manager.product, @web_illumination_site.indexer.product]
      tags:
          - { name: doctrine.event_listener, event: prePersist, method: prePersist }
          - { name: doctrine.event_listener, event: postPersist, method: postPersist }
          - { name: doctrine.event_listener, event: preUpdate, method: preUpdate }
          - { name: doctrine.event_listener, event: postUpdate, method: postUpdate }
          - { name: doctrine.event_listener, event: postRemove, method: postRemove}
  web_illumination_site.listener.variant:
      class: WebIllumination\SiteBundle\EventListener\VariantListener
      arguments: [@web_illumination_site.manager.product, @web_illumination_site.indexer.product]
      tags:
          - { name: doctrine.event_listener, event: prePersist, method: prePersist }
          - { name: doctrine.event_listener, event: postPersist, method: postPersist }
          - { name: doctrine.event_listener, event: preUpdate, method: preUpdate }
          - { name: doctrine.event_listener, event: postUpdate, method: postUpdate }
          - { name: doctrine.event_listener, event: postRemove, method: postRemove}
  web_illumination_site.listener.image:
      class: WebIllumination\SiteBundle\EventListener\ImageListener
      arguments: [@web_illumination_site.manager.image]
      tags:
          - { name: doctrine.event_listener, event: prePersist, method: prePersist }
          - { name: doctrine.event_listener, event: postPersist, method: postPersist }
          - { name: doctrine.event_listener, event: preUpdate, method: preUpdate }
          - { name: doctrine.event_listener, event: postUpdate, method: postUpdate }
          - { name: doctrine.event_listener, event: preRemove, method: preRemove}
          - { name: doctrine.event_listener, event: postRemove, method: preRemove}

  # Form Services
  web_illumination_site.form.new_product:
    class: WebIllumination\SiteBundle\Form\NewProductType
    tags:
      - { name: form.type, alias: site_new_product }

  web_illumination_site.form.flow.new_product:
    class: WebIllumination\SiteBundle\Form\NewProductFlow
    parent: craue.form.flow
    scope: request
    calls:
      - [ setFormType, [@web_illumination_site.form.new_product]]
  web_illumination_site.form.new_variant:
    class: WebIllumination\SiteBundle\Form\NewVariantType
    tags:
      - { name: form.type, alias: site_new_variant }
  web_illumination_site.form.flow.new_variant:
    class: WebIllumination\SiteBundle\Form\NewVariantFlow
    parent: craue.form.flow
    scope: request
    calls:
      - [ setFormType, [@web_illumination_site.form.new_variant]]