<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class WebIlluminationAdminBundleEntityOrderProxy extends \WebIllumination\AdminBundle\Entity\Order implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function create()
    {
        $this->__load();
        return parent::create();
    }

    public function update()
    {
        $this->__load();
        return parent::update();
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setUserId($userId)
    {
        $this->__load();
        return parent::setUserId($userId);
    }

    public function getUserId()
    {
        $this->__load();
        return parent::getUserId();
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function getStatusColour()
    {
        $this->__load();
        return parent::getStatusColour();
    }

    public function setPaymentType($paymentType)
    {
        $this->__load();
        return parent::setPaymentType($paymentType);
    }

    public function getPaymentType()
    {
        $this->__load();
        return parent::getPaymentType();
    }

    public function getPaymentTypeLogo()
    {
        $this->__load();
        return parent::getPaymentTypeLogo();
    }

    public function setPaymentResponse($paymentResponse)
    {
        $this->__load();
        return parent::setPaymentResponse($paymentResponse);
    }

    public function getPaymentResponse()
    {
        $this->__load();
        return parent::getPaymentResponse();
    }

    public function getPaymentResponseFraudIcon()
    {
        $this->__load();
        return parent::getPaymentResponseFraudIcon();
    }

    public function setDeliveryType($deliveryType)
    {
        $this->__load();
        return parent::setDeliveryType($deliveryType);
    }

    public function getDeliveryType()
    {
        $this->__load();
        return parent::getDeliveryType();
    }

    public function setItems($items)
    {
        $this->__load();
        return parent::setItems($items);
    }

    public function getItems()
    {
        $this->__load();
        return parent::getItems();
    }

    public function setRecommendedRetailPrice($recommendedRetailPrice)
    {
        $this->__load();
        return parent::setRecommendedRetailPrice($recommendedRetailPrice);
    }

    public function getRecommendedRetailPrice()
    {
        $this->__load();
        return parent::getRecommendedRetailPrice();
    }

    public function setSubTotal($subTotal)
    {
        $this->__load();
        return parent::setSubTotal($subTotal);
    }

    public function getSubTotal()
    {
        $this->__load();
        return parent::getSubTotal();
    }

    public function setSavings($savings)
    {
        $this->__load();
        return parent::setSavings($savings);
    }

    public function getSavings()
    {
        $this->__load();
        return parent::getSavings();
    }

    public function setDeliveryCharge($deliveryCharge)
    {
        $this->__load();
        return parent::setDeliveryCharge($deliveryCharge);
    }

    public function getDeliveryCharge()
    {
        $this->__load();
        return parent::getDeliveryCharge();
    }

    public function setDiscount($discount)
    {
        $this->__load();
        return parent::setDiscount($discount);
    }

    public function getDiscount()
    {
        $this->__load();
        return parent::getDiscount();
    }

    public function setVat($vat)
    {
        $this->__load();
        return parent::setVat($vat);
    }

    public function getVat()
    {
        $this->__load();
        return parent::getVat();
    }

    public function setTotal($total)
    {
        $this->__load();
        return parent::setTotal($total);
    }

    public function getTotal()
    {
        $this->__load();
        return parent::getTotal();
    }

    public function setVoucherCode($voucherCode)
    {
        $this->__load();
        return parent::setVoucherCode($voucherCode);
    }

    public function getVoucherCode()
    {
        $this->__load();
        return parent::getVoucherCode();
    }

    public function setGiftVoucherCode($giftVoucherCode)
    {
        $this->__load();
        return parent::setGiftVoucherCode($giftVoucherCode);
    }

    public function getGiftVoucherCode()
    {
        $this->__load();
        return parent::getGiftVoucherCode();
    }

    public function setMembershipCardNumber($membershipCardNumber)
    {
        $this->__load();
        return parent::setMembershipCardNumber($membershipCardNumber);
    }

    public function getMembershipCardNumber()
    {
        $this->__load();
        return parent::getMembershipCardNumber();
    }

    public function setPossibleDiscount($possibleDiscount)
    {
        $this->__load();
        return parent::setPossibleDiscount($possibleDiscount);
    }

    public function getPossibleDiscount()
    {
        $this->__load();
        return parent::getPossibleDiscount();
    }

    public function setNotesCount($notesCount)
    {
        $this->__load();
        return parent::setNotesCount($notesCount);
    }

    public function getNotesCount()
    {
        $this->__load();
        return parent::getNotesCount();
    }

    public function setFirstName($firstName)
    {
        $this->__load();
        return parent::setFirstName($firstName);
    }

    public function getFirstName()
    {
        $this->__load();
        return parent::getFirstName();
    }

    public function setLastName($lastName)
    {
        $this->__load();
        return parent::setLastName($lastName);
    }

    public function getLastName()
    {
        $this->__load();
        return parent::getLastName();
    }

    public function setOrganisationName($organisationName)
    {
        $this->__load();
        return parent::setOrganisationName($organisationName);
    }

    public function getOrganisationName()
    {
        $this->__load();
        return parent::getOrganisationName();
    }

    public function setEmailAddress($emailAddress)
    {
        $this->__load();
        return parent::setEmailAddress($emailAddress);
    }

    public function getEmailAddress()
    {
        $this->__load();
        return parent::getEmailAddress();
    }

    public function setTelephoneDaytime($telephoneDaytime)
    {
        $this->__load();
        return parent::setTelephoneDaytime($telephoneDaytime);
    }

    public function getTelephoneDaytime()
    {
        $this->__load();
        return parent::getTelephoneDaytime();
    }

    public function setTelephoneEvening($telephoneEvening)
    {
        $this->__load();
        return parent::setTelephoneEvening($telephoneEvening);
    }

    public function getTelephoneEvening()
    {
        $this->__load();
        return parent::getTelephoneEvening();
    }

    public function setMobile($mobile)
    {
        $this->__load();
        return parent::setMobile($mobile);
    }

    public function getMobile()
    {
        $this->__load();
        return parent::getMobile();
    }

    public function setBillingFirstName($billingFirstName)
    {
        $this->__load();
        return parent::setBillingFirstName($billingFirstName);
    }

    public function getBillingFirstName()
    {
        $this->__load();
        return parent::getBillingFirstName();
    }

    public function setBillingLastName($billingLastName)
    {
        $this->__load();
        return parent::setBillingLastName($billingLastName);
    }

    public function getBillingLastName()
    {
        $this->__load();
        return parent::getBillingLastName();
    }

    public function setBillingOrganisationName($billingOrganisationName)
    {
        $this->__load();
        return parent::setBillingOrganisationName($billingOrganisationName);
    }

    public function getBillingOrganisationName()
    {
        $this->__load();
        return parent::getBillingOrganisationName();
    }

    public function setBillingAddressLine1($billingAddressLine1)
    {
        $this->__load();
        return parent::setBillingAddressLine1($billingAddressLine1);
    }

    public function getBillingAddressLine1()
    {
        $this->__load();
        return parent::getBillingAddressLine1();
    }

    public function setBillingAddressLine2($billingAddressLine2)
    {
        $this->__load();
        return parent::setBillingAddressLine2($billingAddressLine2);
    }

    public function getBillingAddressLine2()
    {
        $this->__load();
        return parent::getBillingAddressLine2();
    }

    public function setBillingTownCity($billingTownCity)
    {
        $this->__load();
        return parent::setBillingTownCity($billingTownCity);
    }

    public function getBillingTownCity()
    {
        $this->__load();
        return parent::getBillingTownCity();
    }

    public function setBillingCountyState($billingCountyState)
    {
        $this->__load();
        return parent::setBillingCountyState($billingCountyState);
    }

    public function getBillingCountyState()
    {
        $this->__load();
        return parent::getBillingCountyState();
    }

    public function setBillingPostZipCode($billingPostZipCode)
    {
        $this->__load();
        return parent::setBillingPostZipCode($billingPostZipCode);
    }

    public function getBillingPostZipCode()
    {
        $this->__load();
        return parent::getBillingPostZipCode();
    }

    public function setBillingCountryCode($billingCountryCode)
    {
        $this->__load();
        return parent::setBillingCountryCode($billingCountryCode);
    }

    public function getBillingCountryCode()
    {
        $this->__load();
        return parent::getBillingCountryCode();
    }

    public function setDeliveryFirstName($deliveryFirstName)
    {
        $this->__load();
        return parent::setDeliveryFirstName($deliveryFirstName);
    }

    public function getDeliveryFirstName()
    {
        $this->__load();
        return parent::getDeliveryFirstName();
    }

    public function setDeliveryLastName($deliveryLastName)
    {
        $this->__load();
        return parent::setDeliveryLastName($deliveryLastName);
    }

    public function getDeliveryLastName()
    {
        $this->__load();
        return parent::getDeliveryLastName();
    }

    public function setDeliveryOrganisationName($deliveryOrganisationName)
    {
        $this->__load();
        return parent::setDeliveryOrganisationName($deliveryOrganisationName);
    }

    public function getDeliveryOrganisationName()
    {
        $this->__load();
        return parent::getDeliveryOrganisationName();
    }

    public function setDeliveryAddressLine1($deliveryAddressLine1)
    {
        $this->__load();
        return parent::setDeliveryAddressLine1($deliveryAddressLine1);
    }

    public function getDeliveryAddressLine1()
    {
        $this->__load();
        return parent::getDeliveryAddressLine1();
    }

    public function setDeliveryAddressLine2($deliveryAddressLine2)
    {
        $this->__load();
        return parent::setDeliveryAddressLine2($deliveryAddressLine2);
    }

    public function getDeliveryAddressLine2()
    {
        $this->__load();
        return parent::getDeliveryAddressLine2();
    }

    public function setDeliveryTownCity($deliveryTownCity)
    {
        $this->__load();
        return parent::setDeliveryTownCity($deliveryTownCity);
    }

    public function getDeliveryTownCity()
    {
        $this->__load();
        return parent::getDeliveryTownCity();
    }

    public function setDeliveryCountyState($deliveryCountyState)
    {
        $this->__load();
        return parent::setDeliveryCountyState($deliveryCountyState);
    }

    public function getDeliveryCountyState()
    {
        $this->__load();
        return parent::getDeliveryCountyState();
    }

    public function setDeliveryPostZipCode($deliveryPostZipCode)
    {
        $this->__load();
        return parent::setDeliveryPostZipCode($deliveryPostZipCode);
    }

    public function getDeliveryPostZipCode()
    {
        $this->__load();
        return parent::getDeliveryPostZipCode();
    }

    public function setDeliveryCountryCode($deliveryCountryCode)
    {
        $this->__load();
        return parent::setDeliveryCountryCode($deliveryCountryCode);
    }

    public function getDeliveryCountryCode()
    {
        $this->__load();
        return parent::getDeliveryCountryCode();
    }

    public function setEstimatedDeliveryDateRangeStart($estimatedDeliveryDateRangeStart)
    {
        $this->__load();
        return parent::setEstimatedDeliveryDateRangeStart($estimatedDeliveryDateRangeStart);
    }

    public function getEstimatedDeliveryDateRangeStart()
    {
        $this->__load();
        return parent::getEstimatedDeliveryDateRangeStart();
    }

    public function setEstimatedDeliveryDateRangeEnd($estimatedDeliveryDateRangeEnd)
    {
        $this->__load();
        return parent::setEstimatedDeliveryDateRangeEnd($estimatedDeliveryDateRangeEnd);
    }

    public function getEstimatedDeliveryDateRangeEnd()
    {
        $this->__load();
        return parent::getEstimatedDeliveryDateRangeEnd();
    }

    public function setOrderPrinted($orderPrinted)
    {
        $this->__load();
        return parent::setOrderPrinted($orderPrinted);
    }

    public function getOrderPrinted()
    {
        $this->__load();
        return parent::getOrderPrinted();
    }

    public function setDeliveryNotePrinted($deliveryNotePrinted)
    {
        $this->__load();
        return parent::setDeliveryNotePrinted($deliveryNotePrinted);
    }

    public function getDeliveryNotePrinted()
    {
        $this->__load();
        return parent::getDeliveryNotePrinted();
    }

    public function setActioned($actioned)
    {
        $this->__load();
        return parent::setActioned($actioned);
    }

    public function getActioned()
    {
        $this->__load();
        return parent::getActioned();
    }

    public function setFraudCheckCustomerOrdered($fraudCheckCustomerOrdered)
    {
        $this->__load();
        return parent::setFraudCheckCustomerOrdered($fraudCheckCustomerOrdered);
    }

    public function getFraudCheckCustomerOrdered()
    {
        $this->__load();
        return parent::getFraudCheckCustomerOrdered();
    }

    public function setFraudCheckAddressMatch($fraudCheckAddressMatch)
    {
        $this->__load();
        return parent::setFraudCheckAddressMatch($fraudCheckAddressMatch);
    }

    public function getFraudCheckAddressMatch()
    {
        $this->__load();
        return parent::getFraudCheckAddressMatch();
    }

    public function setFraudCheckNameUsedOnDifferentOrder($fraudCheckNameUsedOnDifferentOrder)
    {
        $this->__load();
        return parent::setFraudCheckNameUsedOnDifferentOrder($fraudCheckNameUsedOnDifferentOrder);
    }

    public function getFraudCheckNameUsedOnDifferentOrder()
    {
        $this->__load();
        return parent::getFraudCheckNameUsedOnDifferentOrder();
    }

    public function setFraudCheckPostZipCodeUsedOnDifferentOrder($fraudCheckPostZipCodeUsedOnDifferentOrder)
    {
        $this->__load();
        return parent::setFraudCheckPostZipCodeUsedOnDifferentOrder($fraudCheckPostZipCodeUsedOnDifferentOrder);
    }

    public function getFraudCheckPostZipCodeUsedOnDifferentOrder()
    {
        $this->__load();
        return parent::getFraudCheckPostZipCodeUsedOnDifferentOrder();
    }

    public function setFraudCheckTelephoneUsedOnDifferentOrder($fraudCheckTelephoneUsedOnDifferentOrder)
    {
        $this->__load();
        return parent::setFraudCheckTelephoneUsedOnDifferentOrder($fraudCheckTelephoneUsedOnDifferentOrder);
    }

    public function getFraudCheckTelephoneUsedOnDifferentOrder()
    {
        $this->__load();
        return parent::getFraudCheckTelephoneUsedOnDifferentOrder();
    }

    public function setCreatedAt($createdAt)
    {
        $this->__load();
        return parent::setCreatedAt($createdAt);
    }

    public function getCreatedAt()
    {
        $this->__load();
        return parent::getCreatedAt();
    }

    public function setUpdatedAt($updatedAt)
    {
        $this->__load();
        return parent::setUpdatedAt($updatedAt);
    }

    public function getUpdatedAt()
    {
        $this->__load();
        return parent::getUpdatedAt();
    }

    public function setMembershipCardPurchased($membershipCardPurchased)
    {
        $this->__load();
        return parent::setMembershipCardPurchased($membershipCardPurchased);
    }

    public function getMembershipCardPurchased()
    {
        $this->__load();
        return parent::getMembershipCardPurchased();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'userId', 'status', 'paymentType', 'paymentResponse', 'deliveryType', 'items', 'recommendedRetailPrice', 'subTotal', 'savings', 'deliveryCharge', 'discount', 'vat', 'total', 'voucherCode', 'giftVoucherCode', 'membershipCardPurchased', 'membershipCardNumber', 'possibleDiscount', 'notesCount', 'firstName', 'lastName', 'organisationName', 'emailAddress', 'telephoneDaytime', 'telephoneEvening', 'mobile', 'billingFirstName', 'billingLastName', 'billingOrganisationName', 'billingAddressLine1', 'billingAddressLine2', 'billingTownCity', 'billingCountyState', 'billingPostZipCode', 'billingCountryCode', 'deliveryFirstName', 'deliveryLastName', 'deliveryOrganisationName', 'deliveryAddressLine1', 'deliveryAddressLine2', 'deliveryTownCity', 'deliveryCountyState', 'deliveryPostZipCode', 'deliveryCountryCode', 'estimatedDeliveryDateRangeStart', 'estimatedDeliveryDateRangeEnd', 'orderPrinted', 'deliveryNotePrinted', 'actioned', 'fraudCheckCustomerOrdered', 'fraudCheckAddressMatch', 'fraudCheckNameUsedOnDifferentOrder', 'fraudCheckPostZipCodeUsedOnDifferentOrder', 'fraudCheckTelephoneUsedOnDifferentOrder', 'createdAt', 'updatedAt');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}