<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class WebIlluminationAdminBundleEntityMembershipCardProxy extends \WebIllumination\AdminBundle\Entity\MembershipCard implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function create()
    {
        $this->__load();
        return parent::create();
    }

    public function update()
    {
        $this->__load();
        return parent::update();
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setUserId($userId)
    {
        $this->__load();
        return parent::setUserId($userId);
    }

    public function getUserId()
    {
        $this->__load();
        return parent::getUserId();
    }

    public function setActive($active)
    {
        $this->__load();
        return parent::setActive($active);
    }

    public function getActive()
    {
        $this->__load();
        return parent::getActive();
    }

    public function getActiveColour()
    {
        $this->__load();
        return parent::getActiveColour();
    }

    public function getActiveIcon()
    {
        $this->__load();
        return parent::getActiveIcon();
    }

    public function setMembershipNumber($membershipNumber)
    {
        $this->__load();
        return parent::setMembershipNumber($membershipNumber);
    }

    public function getMembershipNumber()
    {
        $this->__load();
        return parent::getMembershipNumber();
    }

    public function setItems($items)
    {
        $this->__load();
        return parent::setItems($items);
    }

    public function getItems()
    {
        $this->__load();
        return parent::getItems();
    }

    public function setSubTotal($subTotal)
    {
        $this->__load();
        return parent::setSubTotal($subTotal);
    }

    public function getSubTotal()
    {
        $this->__load();
        return parent::getSubTotal();
    }

    public function setSavings($savings)
    {
        $this->__load();
        return parent::setSavings($savings);
    }

    public function getSavings()
    {
        $this->__load();
        return parent::getSavings();
    }

    public function setCreatedAt($createdAt)
    {
        $this->__load();
        return parent::setCreatedAt($createdAt);
    }

    public function getCreatedAt()
    {
        $this->__load();
        return parent::getCreatedAt();
    }

    public function setUpdatedAt($updatedAt)
    {
        $this->__load();
        return parent::setUpdatedAt($updatedAt);
    }

    public function getUpdatedAt()
    {
        $this->__load();
        return parent::getUpdatedAt();
    }

    public function setValidFromDate($validFromDate)
    {
        $this->__load();
        return parent::setValidFromDate($validFromDate);
    }

    public function getValidFromDate()
    {
        $this->__load();
        return parent::getValidFromDate();
    }

    public function setExpiryDate($expiryDate)
    {
        $this->__load();
        return parent::setExpiryDate($expiryDate);
    }

    public function getExpiryDate()
    {
        $this->__load();
        return parent::getExpiryDate();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'userId', 'active', 'membershipNumber', 'items', 'subTotal', 'savings', 'validFromDate', 'expiryDate', 'createdAt', 'updatedAt');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}