<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class WebIlluminationAdminBundleEntityProductProxy extends \WebIllumination\AdminBundle\Entity\Product implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function create()
    {
        $this->__load();
        return parent::create();
    }

    public function update()
    {
        $this->__load();
        return parent::update();
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setAvailableForPurchase($availableForPurchase)
    {
        $this->__load();
        return parent::setAvailableForPurchase($availableForPurchase);
    }

    public function getAvailableForPurchase()
    {
        $this->__load();
        return parent::getAvailableForPurchase();
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function getStatusColour()
    {
        $this->__load();
        return parent::getStatusColour();
    }

    public function setBrandId($brandId)
    {
        $this->__load();
        return parent::setBrandId($brandId);
    }

    public function getBrandId()
    {
        $this->__load();
        return parent::getBrandId();
    }

    public function setProductCode($productCode)
    {
        $this->__load();
        return parent::setProductCode($productCode);
    }

    public function getProductCode()
    {
        $this->__load();
        return parent::getProductCode();
    }

    public function setAlternativeProductCodes($alternativeProductCodes)
    {
        $this->__load();
        return parent::setAlternativeProductCodes($alternativeProductCodes);
    }

    public function getAlternativeProductCodes()
    {
        $this->__load();
        return parent::getAlternativeProductCodes();
    }

    public function setFeatureComparison($featureComparison)
    {
        $this->__load();
        return parent::setFeatureComparison($featureComparison);
    }

    public function getFeatureComparison()
    {
        $this->__load();
        return parent::getFeatureComparison();
    }

    public function setDownloadable($downloadable)
    {
        $this->__load();
        return parent::setDownloadable($downloadable);
    }

    public function getDownloadable()
    {
        $this->__load();
        return parent::getDownloadable();
    }

    public function setMembershipCardDiscountAvailable($membershipCardDiscountAvailable)
    {
        $this->__load();
        return parent::setMembershipCardDiscountAvailable($membershipCardDiscountAvailable);
    }

    public function getMembershipCardDiscountAvailable()
    {
        $this->__load();
        return parent::getMembershipCardDiscountAvailable();
    }

    public function setMaximumMembershipCardDiscount($maximumMembershipCardDiscount)
    {
        $this->__load();
        return parent::setMaximumMembershipCardDiscount($maximumMembershipCardDiscount);
    }

    public function getMaximumMembershipCardDiscount()
    {
        $this->__load();
        return parent::getMaximumMembershipCardDiscount();
    }

    public function setMpn($mpn)
    {
        $this->__load();
        return parent::setMpn($mpn);
    }

    public function getMpn()
    {
        $this->__load();
        return parent::getMpn();
    }

    public function setEan($ean)
    {
        $this->__load();
        return parent::setEan($ean);
    }

    public function getEan()
    {
        $this->__load();
        return parent::getEan();
    }

    public function setUpc($upc)
    {
        $this->__load();
        return parent::setUpc($upc);
    }

    public function getUpc()
    {
        $this->__load();
        return parent::getUpc();
    }

    public function setJan($jan)
    {
        $this->__load();
        return parent::setJan($jan);
    }

    public function getJan()
    {
        $this->__load();
        return parent::getJan();
    }

    public function setIsbn($isbn)
    {
        $this->__load();
        return parent::setIsbn($isbn);
    }

    public function getIsbn()
    {
        $this->__load();
        return parent::getIsbn();
    }

    public function setWeight($weight)
    {
        $this->__load();
        return parent::setWeight($weight);
    }

    public function getWeight()
    {
        $this->__load();
        return parent::getWeight();
    }

    public function setLength($length)
    {
        $this->__load();
        return parent::setLength($length);
    }

    public function getLength()
    {
        $this->__load();
        return parent::getLength();
    }

    public function setWidth($width)
    {
        $this->__load();
        return parent::setWidth($width);
    }

    public function getWidth()
    {
        $this->__load();
        return parent::getWidth();
    }

    public function setHeight($height)
    {
        $this->__load();
        return parent::setHeight($height);
    }

    public function getHeight()
    {
        $this->__load();
        return parent::getHeight();
    }

    public function setHidePrice($hidePrice)
    {
        $this->__load();
        return parent::setHidePrice($hidePrice);
    }

    public function getHidePrice()
    {
        $this->__load();
        return parent::getHidePrice();
    }

    public function setShowPriceOutOfHours($showPriceOutOfHours)
    {
        $this->__load();
        return parent::setShowPriceOutOfHours($showPriceOutOfHours);
    }

    public function getShowPriceOutOfHours()
    {
        $this->__load();
        return parent::getShowPriceOutOfHours();
    }

    public function setSpecialOffer($specialOffer)
    {
        $this->__load();
        return parent::setSpecialOffer($specialOffer);
    }

    public function getSpecialOffer()
    {
        $this->__load();
        return parent::getSpecialOffer();
    }

    public function setCreatedAt($createdAt)
    {
        $this->__load();
        return parent::setCreatedAt($createdAt);
    }

    public function getCreatedAt()
    {
        $this->__load();
        return parent::getCreatedAt();
    }

    public function setUpdatedAt($updatedAt)
    {
        $this->__load();
        return parent::setUpdatedAt($updatedAt);
    }

    public function getUpdatedAt()
    {
        $this->__load();
        return parent::getUpdatedAt();
    }

    public function setRecommended($recommended)
    {
        $this->__load();
        return parent::setRecommended($recommended);
    }

    public function getRecommended()
    {
        $this->__load();
        return parent::getRecommended();
    }

    public function setAccessory($accessory)
    {
        $this->__load();
        return parent::setAccessory($accessory);
    }

    public function getAccessory()
    {
        $this->__load();
        return parent::getAccessory();
    }

    public function setNew($new)
    {
        $this->__load();
        return parent::setNew($new);
    }

    public function getNew()
    {
        $this->__load();
        return parent::getNew();
    }

    public function setDeliveryBand($deliveryBand)
    {
        $this->__load();
        return parent::setDeliveryBand($deliveryBand);
    }

    public function getDeliveryBand()
    {
        $this->__load();
        return parent::getDeliveryBand();
    }

    public function setDeliveryCost($deliveryCost)
    {
        $this->__load();
        return parent::setDeliveryCost($deliveryCost);
    }

    public function getDeliveryCost()
    {
        $this->__load();
        return parent::getDeliveryCost();
    }

    public function setProductGroupId($productGroupId)
    {
        $this->__load();
        return parent::setProductGroupId($productGroupId);
    }

    public function getProductGroupId()
    {
        $this->__load();
        return parent::getProductGroupId();
    }

    public function setChecked($checked)
    {
        $this->__load();
        return parent::setChecked($checked);
    }

    public function getChecked()
    {
        $this->__load();
        return parent::getChecked();
    }

    public function setSampleRequest($sampleRequest)
    {
        $this->__load();
        return parent::setSampleRequest($sampleRequest);
    }

    public function getSampleRequest()
    {
        $this->__load();
        return parent::getSampleRequest();
    }

    public function setLastChecked($lastChecked)
    {
        $this->__load();
        return parent::setLastChecked($lastChecked);
    }

    public function getLastChecked()
    {
        $this->__load();
        return parent::getLastChecked();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'productGroupId', 'status', 'checked', 'availableForPurchase', 'brandId', 'productCode', 'alternativeProductCodes', 'featureComparison', 'downloadable', 'specialOffer', 'recommended', 'accessory', 'new', 'membershipCardDiscountAvailable', 'maximumMembershipCardDiscount', 'mpn', 'ean', 'upc', 'jan', 'isbn', 'weight', 'length', 'width', 'height', 'deliveryBand', 'deliveryCost', 'sampleRequest', 'hidePrice', 'showPriceOutOfHours', 'lastChecked', 'createdAt', 'updatedAt');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}