<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class WebIlluminationAdminBundleEntityContactAddressProxy extends \WebIllumination\AdminBundle\Entity\ContactAddress implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function create()
    {
        $this->__load();
        return parent::create();
    }

    public function update()
    {
        $this->__load();
        return parent::update();
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setContactAddressTypeId($contactAddressTypeId)
    {
        $this->__load();
        return parent::setContactAddressTypeId($contactAddressTypeId);
    }

    public function getContactAddressTypeId()
    {
        $this->__load();
        return parent::getContactAddressTypeId();
    }

    public function setContactId($contactId)
    {
        $this->__load();
        return parent::setContactId($contactId);
    }

    public function getContactId()
    {
        $this->__load();
        return parent::getContactId();
    }

    public function setDisplayOrder($displayOrder)
    {
        $this->__load();
        return parent::setDisplayOrder($displayOrder);
    }

    public function getDisplayOrder()
    {
        $this->__load();
        return parent::getDisplayOrder();
    }

    public function setDisplayName($displayName)
    {
        $this->__load();
        return parent::setDisplayName($displayName);
    }

    public function getDisplayName()
    {
        $this->__load();
        return parent::getDisplayName();
    }

    public function setOrganisationName($organisationName)
    {
        $this->__load();
        return parent::setOrganisationName($organisationName);
    }

    public function getOrganisationName()
    {
        $this->__load();
        return parent::getOrganisationName();
    }

    public function setContactTitleId($contactTitleId)
    {
        $this->__load();
        return parent::setContactTitleId($contactTitleId);
    }

    public function getContactTitleId()
    {
        $this->__load();
        return parent::getContactTitleId();
    }

    public function setFirstName($firstName)
    {
        $this->__load();
        return parent::setFirstName($firstName);
    }

    public function getFirstName()
    {
        $this->__load();
        return parent::getFirstName();
    }

    public function setMiddleName($middleName)
    {
        $this->__load();
        return parent::setMiddleName($middleName);
    }

    public function getMiddleName()
    {
        $this->__load();
        return parent::getMiddleName();
    }

    public function setLastName($lastName)
    {
        $this->__load();
        return parent::setLastName($lastName);
    }

    public function getLastName()
    {
        $this->__load();
        return parent::getLastName();
    }

    public function setAddressLine1($addressLine1)
    {
        $this->__load();
        return parent::setAddressLine1($addressLine1);
    }

    public function getAddressLine1()
    {
        $this->__load();
        return parent::getAddressLine1();
    }

    public function setAddressLine2($addressLine2)
    {
        $this->__load();
        return parent::setAddressLine2($addressLine2);
    }

    public function getAddressLine2()
    {
        $this->__load();
        return parent::getAddressLine2();
    }

    public function setAddressLine3($addressLine3)
    {
        $this->__load();
        return parent::setAddressLine3($addressLine3);
    }

    public function getAddressLine3()
    {
        $this->__load();
        return parent::getAddressLine3();
    }

    public function setTownCity($townCity)
    {
        $this->__load();
        return parent::setTownCity($townCity);
    }

    public function getTownCity()
    {
        $this->__load();
        return parent::getTownCity();
    }

    public function setCountyState($countyState)
    {
        $this->__load();
        return parent::setCountyState($countyState);
    }

    public function getCountyState()
    {
        $this->__load();
        return parent::getCountyState();
    }

    public function setPostZipCode($postZipCode)
    {
        $this->__load();
        return parent::setPostZipCode($postZipCode);
    }

    public function getPostZipCode()
    {
        $this->__load();
        return parent::getPostZipCode();
    }

    public function setCountryCode($countryCode)
    {
        $this->__load();
        return parent::setCountryCode($countryCode);
    }

    public function getCountryCode()
    {
        $this->__load();
        return parent::getCountryCode();
    }

    public function setCreatedAt($createdAt)
    {
        $this->__load();
        return parent::setCreatedAt($createdAt);
    }

    public function getCreatedAt()
    {
        $this->__load();
        return parent::getCreatedAt();
    }

    public function setUpdatedAt($updatedAt)
    {
        $this->__load();
        return parent::setUpdatedAt($updatedAt);
    }

    public function getUpdatedAt()
    {
        $this->__load();
        return parent::getUpdatedAt();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'contactAddressTypeId', 'contactId', 'displayOrder', 'displayName', 'organisationName', 'contactTitleId', 'firstName', 'middleName', 'lastName', 'addressLine1', 'addressLine2', 'addressLine3', 'townCity', 'countyState', 'postZipCode', 'countryCode', 'createdAt', 'updatedAt');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}