<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class WebIlluminationAdminBundleEntityDepartmentProxy extends \WebIllumination\AdminBundle\Entity\Department implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function create()
    {
        $this->__load();
        return parent::create();
    }

    public function update()
    {
        $this->__load();
        return parent::update();
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setParentId($parentId)
    {
        $this->__load();
        return parent::setParentId($parentId);
    }

    public function getParentId()
    {
        $this->__load();
        return parent::getParentId();
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function getStatusColour()
    {
        $this->__load();
        return parent::getStatusColour();
    }

    public function setDepartmentPath($departmentPath)
    {
        $this->__load();
        return parent::setDepartmentPath($departmentPath);
    }

    public function getDepartmentPath()
    {
        $this->__load();
        return parent::getDepartmentPath();
    }

    public function setHidePrices($hidePrices)
    {
        $this->__load();
        return parent::setHidePrices($hidePrices);
    }

    public function getHidePrices()
    {
        $this->__load();
        return parent::getHidePrices();
    }

    public function setShowPricesOutOfHours($showPricesOutOfHours)
    {
        $this->__load();
        return parent::setShowPricesOutOfHours($showPricesOutOfHours);
    }

    public function getShowPricesOutOfHours()
    {
        $this->__load();
        return parent::getShowPricesOutOfHours();
    }

    public function setDisplayOrder($displayOrder)
    {
        $this->__load();
        return parent::setDisplayOrder($displayOrder);
    }

    public function getDisplayOrder()
    {
        $this->__load();
        return parent::getDisplayOrder();
    }

    public function setCreatedAt($createdAt)
    {
        $this->__load();
        return parent::setCreatedAt($createdAt);
    }

    public function getCreatedAt()
    {
        $this->__load();
        return parent::getCreatedAt();
    }

    public function setUpdatedAt($updatedAt)
    {
        $this->__load();
        return parent::setUpdatedAt($updatedAt);
    }

    public function getUpdatedAt()
    {
        $this->__load();
        return parent::getUpdatedAt();
    }

    public function setMembershipCardDiscountAvailable($membershipCardDiscountAvailable)
    {
        $this->__load();
        return parent::setMembershipCardDiscountAvailable($membershipCardDiscountAvailable);
    }

    public function getMembershipCardDiscountAvailable()
    {
        $this->__load();
        return parent::getMembershipCardDiscountAvailable();
    }

    public function setMaximumMembershipCardDiscount($maximumMembershipCardDiscount)
    {
        $this->__load();
        return parent::setMaximumMembershipCardDiscount($maximumMembershipCardDiscount);
    }

    public function getMaximumMembershipCardDiscount()
    {
        $this->__load();
        return parent::getMaximumMembershipCardDiscount();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'parentId', 'status', 'departmentPath', 'hidePrices', 'showPricesOutOfHours', 'membershipCardDiscountAvailable', 'maximumMembershipCardDiscount', 'displayOrder', 'createdAt', 'updatedAt');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}