imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: imagine.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      
        engines: ['twig']
        packages:
            cdn:
                base_urls:
                    http: ["%cdn_host%"]
                    ssl: ["%cdn_ssl_host%"]
            nocdn:
                base_urls:
                    http: ["%host%"]
                    ssl: ["%ssl_host%"]
        assets_base_urls:
            http: ["%cdn_host%"]
            ssl: ["%cdn_ssl_host%"]
    default_locale:  "%locale%"
    session: ~

# Twig Configuration
twig:
    cache:                "%kernel.cache_dir%/twig"
    debug:                "%kernel.debug%"
    form:
        resources:
            - 'KACSiteBundle::fields.html.twig'
    globals:
        social_media_twitter_username:   "%social_media.twitter.username%"
        social_media_facebook_username:  "%social_media.facebook.username%"
        google_analytics_account_number: "%google.analytics.account_number%"
        company_name:                    "%company.name%"
        company_web_address:             "%company.web_address%"
        company_url:                     "%company.url%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [KACSiteBundle,WebIlluminationAdminBundle]
#    bundles:        [KACShopBundle,KACAdminBundle]
    filters:
        sass: ~
        compass:
            plugins:
                - 'rgbapng'
        cssrewrite: ~
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  utf8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true
                metadata_cache_driver: apc
                query_cache_driver: apc
                result_cache_driver: apc
                mappings:
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        alias: GedmoTree # this one is optional and will default to the name set for the mapping
                        is_bundle: false

# Doctrine Extensions Configuration
stof_doctrine_extensions:
    default_locale: "%locale%"
    orm:
        default:
            tree: true
            timestampable: true
            uploadable: true
    uploadable:
        default_file_path:       %kernel.root_dir%/../web/uploads
        mime_type_guesser_class: Stof\DoctrineExtensionsBundle\Uploadable\MimeTypeGuesserAdapter
        default_file_info_class: Stof\DoctrineExtensionsBundle\Uploadable\UploadedFileInfo

# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    spool:      { type: memory }
    port:       587
    encryption: tls

knp_snappy:
    pdf:
        enabled:    true
        binary:     /usr/bin/wkhtmltopdf-i386
        options:    []

nelmio_solarium:
    default_client: product
    clients:
        product:
            host: "%solr_host%"
            port: "%solr_port%"
            path: "%solr_path%"
            core: products
            timeout: 5

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: KAC\UserBundle\Entity\User
    registration:
        form:
            type: kac_user_registration
    service:
        user_manager: kac.user_manager.default

gregwar_form: ~

trsteel_ckeditor:
    class: Trsteel\CkeditorBundle\Form\Type\CkeditorType
    transformers: ['strip_js', 'strip_css', 'strip_comments']
    force_paste_as_plaintext: true
    toolbar: ['font', 'lists', 'history', 'source']
    toolbar_groups:
        font: ['Bold','Italic','Underline']
        lists: ['NumberedList','BulletedList','Outdent','Indent']
        history: ['Undo','Redo']
        source: ['Source']
    ui_color: '#c5d2d6'
    startup_outline_blocks: false
    language: 'en-gb'