imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      
        engines: ['twig']
        packages:
            cdn:
                base_urls:
                    http: [http://staging.kitchenappliancecentre.co.uk]
                    ssl: [http://staging.kitchenappliancecentre.co.uk]
            nocdn:
                base_urls:
                    http: [http://staging.kitchenappliancecentre.co.uk]
                    ssl: [http://staging.kitchenappliancecentre.co.uk]
        assets_base_urls:
            http: [http://staging.kitchenappliancecentre.co.uk]
            ssl: [http://staging.kitchenappliancecentre.co.uk]
    default_locale:  "%locale%"
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    cache:                "%kernel.cache_dir%/twig"
    debug:                "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [WebIlluminationShopBundle,WebIlluminationAdminBundle]
    filters:
        cssrewrite: ~
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  utf8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        metadata_cache_driver: apc
        query_cache_driver: apc
        result_cache_driver: apc

# Doctrine Extensions Configuration
stof_doctrine_extensions:
    default_locale: "%locale%"
    orm:
        default: ~

# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    spool:      { type: memory }
    port:       587
    encryption: tls

knp_snappy:
    pdf:
        enabled:    true
        binary:     /usr/bin/wkhtmltopdf-i386
        options:    []

nelmio_solarium:
    default_client: product
    clients:
        product:
            host: "%solr_host%"
            port: "%solr_port%"
            path: "%solr_path%"
            core: products
            timeout: 5