avalanche_imagine:
    filters:
        # Logos
        logo_thumbnail:
            type:   thumbnail
            options: { size: [50, 25], mode: inset, quality: 60 }
        logo_medium:
            type:   resize
            options: { size: [100, 50], quality: 100 }
        logo_large:
            type:   resize
            options: { size: [300, 150], quality: 100 }
        # Logos
        gallery_thumbnail:
            type:   thumbnail
            options: { size: [170, 50], mode: inset, quality: 60 }
        gallery_medium:
            type:   resize
            options: { size: [300, 86], quality: 100 }
        gallery_large:
            type:   resize
            options: { size: [978, 400], quality: 100 }
        # Logos
        product_thumbnail:
            type:   thumbnail
            options: { size: [100, 100], mode: inset, quality: 60 }
        product_medium:
            type:   resize
            options: { size: [300, 300], quality: 100 }
        product_large:
            type:   resize
            options: { size: [800, 600], quality: 100 }