parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     kac
    database_user:     kac
    database_password: D3rbysh1r3

    solr_host:         localhost
    solr_port:         8080
    solr_path:          /solr3

    mailer_transport:  smtp
    mailer_host:       mail.ridedirect.co.uk
    mailer_user:       sales@ridedirect.co.uk
    mailer_password:   madelaine12

    locale:            en
    secret:            90f229762b755dda3c62e49b328f84cd9c126a22
