_welcome:
    pattern:  /
    defaults: { _controller: WebIlluminationSiteBundle:Content:index }

#WebIlluminationShopBundle:
#    resource: "@WebIlluminationShopBundle/Resources/config/routing.yml"
#    prefix:   /
#
#WebIlluminationAdminBundle:
#    resource: "@WebIlluminationAdminBundle/Resources/config/routing.yml"
#    prefix:   /

web_illumination_shop:
    resource: "@WebIlluminationSiteBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /account

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /account

_imagine:
    resource: .
    type:     imagine
