jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER:        ROLE_GUEST
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                use_referer:        true
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/checkout/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/orders/importTracking/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/orders/viewOrder/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/orders/viewDeliveryNote/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/orders/viewInvoice/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/orders/viewCopyOrder/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/.*, roles: ROLE_ADMIN, requires_channel: http }
        - { path: ^/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN