# Bugs
admin_bugs:
    pattern:   /admin/bugs
    defaults:  { _controller: WebIlluminationAdminBundle:Bugs:index }
admin_bugs_update_listing:
    pattern:   /admin/bugs/updateListing
    defaults:  { _controller: WebIlluminationAdminBundle:Bugs:updateListing }
admin_bugs_add:
    pattern:   /admin/bugs/add
    defaults:  { _controller: WebIlluminationAdminBundle:Bugs:add }
admin_bugs_update:
    pattern:   /admin/bugs/update/{id}
    defaults:  { _controller: WebIlluminationAdminBundle:Bugs:update, id: 0 }
admin_bugs_delete:
    pattern:   /admin/bugs/delete/{id}
    defaults:  { _controller: WebIlluminationAdminBundle:Bugs:delete, id: 0 }
    
# Orders
admin_orders:
    pattern:   /admin/orders
    defaults:  { _controller: WebIlluminationAdminBundle:Orders:index }
admin_orders_update_listing:
    pattern:   /admin/orders/updateListing
    defaults:  { _controller: WebIlluminationAdminBundle:Orders:updateListing }
admin_orders_ajax_get_customer:
    pattern:   /admin/orders/ajaxGetCustomer
    defaults:  { _controller: WebIlluminationAdminBundle:Orders:ajaxGetCustomer }
admin_orders_ajax_get_delivery_information:
    pattern:   /admin/orders/ajaxGetDeliveryInformation
    defaults:  { _controller: WebIlluminationAdminBundle:Orders:ajaxGetDeliveryInformation }
admin_orders_ajax_get_documents:
    pattern:   /admin/orders/ajaxGetDocuments
    defaults:  { _controller: WebIlluminationAdminBundle:Orders:ajaxGetDocuments }
admin_orders_ajax_get_notes:
    pattern:   /admin/orders/ajaxGetNotes
    defaults:  { _controller: WebIlluminationAdminBundle:Orders:ajaxGetNotes }
admin_orders_ajax_get_payment_information:
    pattern:   /admin/orders/ajaxGetPaymentInformation
    defaults:  { _controller: WebIlluminationAdminBundle:Orders:ajaxGetPaymentInformation }
admin_orders_ajax_get_products:
    pattern:   /admin/orders/ajaxGetProducts
    defaults:  { _controller: WebIlluminationAdminBundle:Orders:ajaxGetProducts }
admin_orders_ajax_get_statistics:
    pattern:   /admin/orders/ajaxGetStatistics
    defaults:  { _controller: WebIlluminationAdminBundle:Orders:ajaxGetStatistics }
admin_orders_process_deliveries:
    pattern:   /admin/orders/processDeliveries
    defaults:  { _controller: WebIlluminationAdminBundle:Orders:processDeliveries }
admin_orders_import_tracking:
    pattern:   /admin/orders/importTracking
    defaults:  { _controller: WebIlluminationAdminBundle:Orders:importTracking }
admin_orders_add:
    pattern:   /admin/orders/add
    defaults:  { _controller: WebIlluminationAdminBundle:Orders:add }
admin_orders_update:
    pattern:   /admin/orders/update/{id}
    defaults:  { _controller: WebIlluminationAdminBundle:Orders:update, id: 0 }
admin_orders_update_payment:
    pattern:   /admin/orders/updatePayment/{id}
    defaults:  { _controller: WebIlluminationAdminBundle:Orders:updatePayment, id: 0 }
admin_orders_update_delivery:
    pattern:   /admin/orders/updateDelivery/{id}
    defaults:  { _controller: WebIlluminationAdminBundle:Orders:updateDelivery, id: 0 }
admin_orders_update_products:
    pattern:   /admin/orders/updateProducts/{id}
    defaults:  { _controller: WebIlluminationAdminBundle:Orders:updateProducts, id: 0 }
admin_orders_update_notes:
    pattern:   /admin/orders/updateNotes/{id}
    defaults:  { _controller: WebIlluminationAdminBundle:Orders:updateNotes, id: 0 }
admin_orders_delete:
    pattern:   /admin/orders/delete/{id}
    defaults:  { _controller: WebIlluminationAdminBundle:Orders:delete, id: 0 }
admin_orders_view_copy_order:
    pattern:  /admin/orders/viewCopyOrder/{id}
    defaults: { _controller: WebIlluminationAdminBundle:Orders:viewCopyOrder, id: 0 }
admin_orders_view_delivery_note:
    pattern:  /admin/orders/viewDeliveryNote/{id}
    defaults: { _controller: WebIlluminationAdminBundle:Orders:viewDeliveryNote, id: 0 }
admin_orders_view_invoice:
    pattern:  /admin/orders/viewInvoice/{id}
    defaults: { _controller: WebIlluminationAdminBundle:Orders:viewInvoice, id: 0 }
admin_orders_view_order:
    pattern:  /admin/orders/viewOrder/{id}
    defaults: { _controller: WebIlluminationAdminBundle:Orders:viewOrder, id: 0 }

# System
system_crawl_errors:
    pattern:  /admin/system/crawlErrors
    defaults: { _controller: WebIlluminationAdminBundle:System:crawlErrors }
system_build_url:
    pattern:  /admin/system/buildUrl
    defaults: { _controller: WebIlluminationAdminBundle:System:buildUrl }
system_ajax_get_url:
    pattern:  /admin/system/ajaxGetUrl
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxGetUrl }    
system_ajax_upload_file:
    pattern:  /admin/system/ajaxUploadFile
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxUploadFile }
system_ajax_get_images:
    pattern:  /admin/system/ajaxGetImages
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxGetImages }
system_ajax_add_image:
    pattern:  /admin/system/ajaxAddImage
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxAddImage }
system_ajax_update_image:
    pattern:  /admin/system/ajaxUpdateImage
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxUpdateImage } 
system_ajax_delete_image:
    pattern:  /admin/system/ajaxDeleteImage
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxDeleteImage }
system_ajax_get_files:
    pattern:  /admin/system/ajaxGetFiles
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxGetFiles }
system_ajax_add_file:
    pattern:  /admin/system/ajaxAddFile
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxAddFile }
system_ajax_update_file:
    pattern:  /admin/system/ajaxUpdateFile
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxUpdateFile } 
system_ajax_delete_file:
    pattern:  /admin/system/ajaxDeleteFile
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxDeleteFile }
system_ajax_get_redirects:
    pattern:  /admin/system/ajaxGetRedirects
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxGetRedirects }
system_ajax_add_redirect:
    pattern:  /admin/system/ajaxAddRedirect
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxAddRedirect }
system_ajax_update_redirect:
    pattern:  /admin/system/ajaxUpdateRedirect
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxUpdateRedirect }
system_ajax_delete_redirect:
    pattern:  /admin/system/ajaxDeleteRedirect
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxDeleteRedirect }
system_ajax_get_guarantees:
    pattern:  /admin/system/ajaxGetGuarantees
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxGetGuarantees }
system_ajax_add_guarantee:
    pattern:  /admin/system/ajaxAddGuarantee
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxAddGuarantee }
system_ajax_update_guarantee:
    pattern:  /admin/system/ajaxUpdateGuarantee
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxUpdateGuarantee }
system_ajax_delete_guarantee:
    pattern:  /admin/system/ajaxDeleteGuarantee
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxDeleteGuarantee }
system_ajax_get_contacts:
    pattern:  /admin/system/ajaxGetContacts
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxGetContacts }
system_ajax_add_contact:
    pattern:  /admin/system/ajaxAddContact
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxAddContact }
system_ajax_update_contact:
    pattern:  /admin/system/ajaxUpdateContact
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxUpdateContact }
system_ajax_delete_contact:
    pattern:  /admin/system/ajaxDeleteContact
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxDeleteContact }
system_ajax_get_contact_numbers:
    pattern:  /admin/system/ajaxGetContactNumbers
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxGetContactNumbers }
system_ajax_add_contact_number:
    pattern:  /admin/system/ajaxAddContactNumber
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxAddContactNumber }
system_ajax_update_contact_number:
    pattern:  /admin/system/ajaxUpdateContactNumber
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxUpdateContactNumber }
system_ajax_delete_contact_number:
    pattern:  /admin/system/ajaxDeleteContactNumber
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxDeleteContactNumber }
system_ajax_get_contact_addresses:
    pattern:  /admin/system/ajaxGetContactAddresses
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxGetContactAddresses }
system_ajax_add_contact_address:
    pattern:  /admin/system/ajaxAddContactAddress
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxAddContactAddress }
system_ajax_update_contact_address:
    pattern:  /admin/system/ajaxUpdateContactAddress
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxUpdateContactAddress }
system_ajax_delete_contact_address:
    pattern:  /admin/system/ajaxDeleteContactAddress
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxDeleteContactAddress }
system_ajax_get_contact_web_addresses:
    pattern:  /admin/system/ajaxGetContactWebAddresses
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxGetContactWebAddresses }
system_ajax_add_contact_web_address:
    pattern:  /admin/system/ajaxAddContactWebAddress
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxAddContactWebAddress }
system_ajax_update_contact_web_address:
    pattern:  /admin/system/ajaxUpdateContactWebAddress
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxUpdateContactWebAddress }
system_ajax_delete_contact_web_address:
    pattern:  /admin/system/ajaxDeleteContactWebAddress
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxDeleteContactWebAddress }
system_ajax_get_contact_email_addresses:
    pattern:  /admin/system/ajaxGetContactEmailAddresses
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxGetContactEmailAddresses }
system_ajax_add_contact_email_address:
    pattern:  /admin/system/ajaxAddContactEmailAddress
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxAddContactEmailAddress }
system_ajax_update_contact_email_address:
    pattern:  /admin/system/ajaxUpdateContactEmailAddress
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxUpdateContactEmailAddress }
system_ajax_delete_contact_email_address:
    pattern:  /admin/system/ajaxDeleteContactEmailAddress
    defaults: { _controller: WebIlluminationAdminBundle:System:ajaxDeleteContactEmailAddress }

# Practice Day Registrations
admin_practice_day_registrations:
    pattern:  /admin/practiceDayRegistrations
    defaults: { _controller: WebIlluminationAdminBundle:PracticeDayRegistrations:index }
admin_practice_day_registrations_ajax_get_listing:
    pattern:  /admin/practiceDayRegistrations/ajaxGetListing
    defaults: { _controller: WebIlluminationAdminBundle:PracticeDayRegistrations:ajaxGetListing }
admin_practice_day_registrations_ajax_get_listing_count:
    pattern:  /admin/practiceDayRegistrations/ajaxGetListingCount
    defaults: { _controller: WebIlluminationAdminBundle:PracticeDayRegistrations:ajaxGetListingCount }
admin_practice_day_registrations_ajax_get_listing_pagination:
    pattern:  /admin/practiceDayRegistrations/ajaxGetListingPagination
    defaults: { _controller: WebIlluminationAdminBundle:PracticeDayRegistrations:ajaxGetListingPagination }
admin_practice_day_registrations_ajax_add_practice_day_registration:
    pattern:  /admin/practiceDayRegistrations/ajaxAddPracticeDayRegistration
    defaults: { _controller: WebIlluminationAdminBundle:PracticeDayRegistrations:ajaxAddPracticeDayRegistration }
admin_practice_day_registrations_ajax_delete_practice_day_registration:
    pattern:  /admin/practiceDayRegistrations/ajaxDeletePracticeDayRegistration
    defaults: { _controller: WebIlluminationAdminBundle:PracticeDayRegistrations:ajaxDeletePracticeDayRegistration }
admin_practice_day_registrations_ajax_save_practice_day_registration:
    pattern:  /admin/practiceDayRegistrations/ajaxSavePracticeDayRegistration
    defaults: { _controller: WebIlluminationAdminBundle:PracticeDayRegistrations:ajaxSavePracticeDayRegistration }
admin_practice_day_registrations_test:
    pattern:  /admin/practiceDayRegistrations/test
    defaults: { _controller: WebIlluminationAdminBundle:PracticeDayRegistrations:test }

# Brands
admin_brands:
    pattern:  /admin/brands
    defaults: { _controller: WebIlluminationAdminBundle:Brands:index }
admin_brands_add:
    pattern:  /admin/brands/add
    defaults: { _controller: WebIlluminationAdminBundle:Brands:add }
admin_brands_update:
    pattern:  /admin/brands/update/{id}
    defaults: { _controller: WebIlluminationAdminBundle:Brands:update, id: 0 }
admin_brands_delete:
    pattern:  /admin/brands/delete/{id}
    defaults: { _controller: WebIlluminationAdminBundle:Brands:delete, id: 0 }
admin_brands_ajax_delete:
    pattern:  /admin/brands/ajaxDelete
    defaults: { _controller: WebIlluminationAdminBundle:Brands:ajaxDelete }
admin_brands_ajax_get_listing:
    pattern:  /admin/brands/ajaxGetListing
    defaults: { _controller: WebIlluminationAdminBundle:Brands:ajaxGetListing }
admin_brands_ajax_get_listing_count:
    pattern:  /admin/brands/ajaxGetListingCount
    defaults: { _controller: WebIlluminationAdminBundle:Brands:ajaxGetListingCount }
admin_brands_ajax_get_listing_pagination:
    pattern:  /admin/brands/ajaxGetListingPagination
    defaults: { _controller: WebIlluminationAdminBundle:Brands:ajaxGetListingPagination }
admin_brands_ajax_update:
    pattern:  /admin/brands/ajaxUpdate
    defaults: { _controller: WebIlluminationAdminBundle:Brands:ajaxUpdate }
admin_brands_ajax_update_general_section:
    pattern:  /admin/brands/ajaxUpdateGeneralSection
    defaults: { _controller: WebIlluminationAdminBundle:Brands:ajaxUpdateGeneralSection }
admin_brands_ajax_delete_logo_image:
    pattern:  /admin/brands/ajaxDeleteLogoImage
    defaults: { _controller: WebIlluminationAdminBundle:Brands:ajaxDeleteLogoImage }
admin_brands_ajax_update_description_section:
    pattern:  /admin/brands/ajaxUpdateDescriptionSection
    defaults: { _controller: WebIlluminationAdminBundle:Brands:ajaxUpdateDescriptionSection }
admin_brands_ajax_get_description:
    pattern:  /admin/brands/ajaxGetDescription
    defaults: { _controller: WebIlluminationAdminBundle:Brands:ajaxGetDescription }
admin_brands_ajax_get_short_description:
    pattern:  /admin/brands/ajaxGetShortDescription
    defaults: { _controller: WebIlluminationAdminBundle:Brands:ajaxGetShortDescription }
admin_brands_ajax_update_price_settings_section:
    pattern:  /admin/brands/ajaxUpdatePriceSettingsSection
    defaults: { _controller: WebIlluminationAdminBundle:Brands:ajaxUpdatePriceSettingsSection }
admin_brands_ajax_update_seo_section:
    pattern:  /admin/brands/ajaxUpdateSeoSection
    defaults: { _controller: WebIlluminationAdminBundle:Brands:ajaxUpdateSeoSection }
admin_brands_ajax_reset_seo:
    pattern:  /admin/brands/ajaxResetSeo
    defaults: { _controller: WebIlluminationAdminBundle:Brands:ajaxResetSeo }

# Data
data:
    pattern:  /admin/data
    defaults: { _controller: WebIlluminationAdminBundle:Data:legacyImport }
data_legacy_import:
    pattern:  /admin/data/legacyImport
    defaults: { _controller: WebIlluminationAdminBundle:Data:legacyImport }
data_ajax_load_legacy_import_data:
    pattern:  /admin/data/ajaxLoadLegacyImportData
    defaults: { _controller: WebIlluminationAdminBundle:Data:ajaxLoadLegacyImportData }