services:
  web_illumination_admin.form.new_product:
    class: WebIllumination\AdminBundle\Form\NewProductType
    tags:
      - { name: form.type, alias: admin_new_product }

  web_illumination_admin.form.flow.new_product:
    class: WebIllumination\AdminBundle\Form\NewProductFlow
    parent: craue.form.flow
    scope: request
    calls:
      - [ setFormType, [@web_illumination_admin.form.new_product]]