services:
  web_illumination_admin.form.new_product_group:
    class: WebIllumination\AdminBundle\Form\NewProductGroupType
    tags:
      - { name: form.type, alias: admin_new_product_group }

  web_illumination_admin.form.flow.new_product_group:
    class: WebIllumination\AdminBundle\Form\NewProductGroupFlow
    parent: craue.form.flow
    scope: request
    calls:
      - [ setFormType, [@web_illumination_admin.form.new_product_group]]
  web_illumination_admin.form.type.feature_group:
      class: WebIllumination\AdminBundle\Form\FeatureGroupType
      arguments:
          - "@doctrine"
      tags:
          - { name: form.type, alias: feature_group }