<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121216162421 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE departments ADD CONSTRAINT FK_16AEB8D4727ACA70 FOREIGN KEY (parent_id) REFERENCES departments (id)");
        $this->addSql("ALTER TABLE brand_descriptions ADD CONSTRAINT FK_4D8F90544F5D008 FOREIGN KEY (brand_id) REFERENCES brands (id)");
        $this->addSql("ALTER TABLE brand_descriptions ADD CONSTRAINT FK_4D8F9056D947EBB FOREIGN KEY (logo_image_id) REFERENCES brands (id)");
        $this->addSql("ALTER TABLE brand_to_department ADD CONSTRAINT FK_B88B579644F5D008 FOREIGN KEY (brand_id) REFERENCES departments (id)");
        $this->addSql("ALTER TABLE brand_to_department ADD CONSTRAINT FK_B88B5796AE80F5DF FOREIGN KEY (department_id) REFERENCES departments (id)");
        $this->addSql("ALTER TABLE product_to_option ADD CONSTRAINT FK_12F4BAA04584665A FOREIGN KEY (product_id) REFERENCES products (id)");
        $this->addSql("ALTER TABLE product_to_option ADD CONSTRAINT FK_12F4BAA0C964ABE2 FOREIGN KEY (product_option_id) REFERENCES product_options (id)");
        $this->addSql("ALTER TABLE products ADD CONSTRAINT FK_B3BA5A5A44F5D008 FOREIGN KEY (brand_id) REFERENCES brands (id)");
        $this->addSql("ALTER TABLE contacts ADD CONSTRAINT FK_3340157390BA1B2A FOREIGN KEY (contact_title_id) REFERENCES contact_titles (id)");
        $this->addSql("ALTER TABLE contact_email_addresses ADD CONSTRAINT FK_FBD6D503E7A1254A FOREIGN KEY (contact_id) REFERENCES contacts (id)");
        $this->addSql("ALTER TABLE contact_email_addresses ADD CONSTRAINT FK_FBD6D5035D408FBE FOREIGN KEY (contact_email_address_type_id) REFERENCES contact_email_address_types (id)");
        $this->addSql("ALTER TABLE contact_web_addresses ADD CONSTRAINT FK_90FEF745E7A1254A FOREIGN KEY (contact_id) REFERENCES contacts (id)");
        $this->addSql("ALTER TABLE contact_web_addresses ADD CONSTRAINT FK_90FEF7451E44B9BB FOREIGN KEY (contact_web_address_type_id) REFERENCES contact_web_address_types (id)");
        $this->addSql("ALTER TABLE contact_numbers ADD CONSTRAINT FK_EDB1EB78E7A1254A FOREIGN KEY (contact_id) REFERENCES contacts (id)");
        $this->addSql("ALTER TABLE contact_numbers ADD CONSTRAINT FK_EDB1EB78C12336C6 FOREIGN KEY (contact_number_type_id) REFERENCES contact_number_types (id)");
        $this->addSql("ALTER TABLE contact_addresses ADD CONSTRAINT FK_13B566DE7A1254A FOREIGN KEY (contact_id) REFERENCES contacts (id)");
        $this->addSql("ALTER TABLE contact_addresses ADD CONSTRAINT FK_13B566D5BE4435 FOREIGN KEY (contact_address_type_id) REFERENCES contact_address_types (id)");
        $this->addSql("ALTER TABLE contact_addresses ADD CONSTRAINT FK_13B566D1D8E2517 FOREIGN KEY (contactTitle_id) REFERENCES contact_titles (id)");
        $this->addSql("ALTER TABLE product_to_feature ADD CONSTRAINT FK_22817B84584665A FOREIGN KEY (product_id) REFERENCES products (id)");
        $this->addSql("ALTER TABLE product_to_feature ADD CONSTRAINT FK_22817B8F383E752 FOREIGN KEY (product_feature_id) REFERENCES product_features (id)");
        $this->addSql("ALTER TABLE bugs ADD CONSTRAINT FK_1E197C9B5CBBC0F FOREIGN KEY (owner_contact_id) REFERENCES contacts (id)");
        $this->addSql("ALTER TABLE bugs ADD CONSTRAINT FK_1E197C9E315F242 FOREIGN KEY (assinged_to_contact_id) REFERENCES contacts (id)");
        $this->addSql("ALTER TABLE guarantees ADD CONSTRAINT FK_935E0475668279F0 FOREIGN KEY (guarantee_type_id) REFERENCES guarantee_types (id)");
        $this->addSql("ALTER TABLE guarantees ADD CONSTRAINT FK_935E0475E2EAD863 FOREIGN KEY (guarantee_length_id) REFERENCES guarantee_lengths (id)");
        $this->addSql("ALTER TABLE product_prices ADD CONSTRAINT FK_86B72CFD4584665A FOREIGN KEY (product_id) REFERENCES products (id)");
        $this->addSql("ALTER TABLE product_links ADD CONSTRAINT FK_70DEDA444584665A FOREIGN KEY (product_id) REFERENCES products (id)");
        $this->addSql("ALTER TABLE product_links ADD CONSTRAINT FK_70DEDA44D240BD1D FOREIGN KEY (linked_product_id) REFERENCES products (id)");
        $this->addSql("ALTER TABLE product_options ADD CONSTRAINT FK_1ECE137ECA8AD7E FOREIGN KEY (product_option_group_id) REFERENCES product_option_groups (id)");
        $this->addSql("ALTER TABLE product_features ADD CONSTRAINT FK_7470B6849351284 FOREIGN KEY (product_feature_group_id) REFERENCES product_feature_groups (id)");
        $this->addSql("ALTER TABLE product_descriptions DROP INDEX FK_44CA8CDD4584665A, ADD UNIQUE INDEX UNIQ_44CA8CDD4584665A (product_id)");
        $this->addSql("ALTER TABLE product_descriptions ADD CONSTRAINT FK_44CA8CDD4584665A FOREIGN KEY (product_id) REFERENCES products (id)");
        $this->addSql("DROP INDEX IDX_5242B8EB6E48E3E9 ON order_products");
        $this->addSql("ALTER TABLE order_products DROP product, DROP url, DROP header, DROP product_code, DROP brand, DROP short_description, DROP quantity, DROP unit_cost, DROP recommended_retail_price, DROP discount, DROP savings, CHANGE productid_id product_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE order_products ADD CONSTRAINT FK_5242B8EB8D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id)");
        $this->addSql("ALTER TABLE order_products ADD CONSTRAINT FK_5242B8EB4584665A FOREIGN KEY (product_id) REFERENCES order_products (id)");
        $this->addSql("CREATE INDEX IDX_5242B8EB4584665A ON order_products (product_id)");
        $this->addSql("ALTER TABLE order_discounts ADD CONSTRAINT FK_40D079408D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id)");
        $this->addSql("ALTER TABLE order_notes ADD CONSTRAINT FK_8285D2718D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id)");
        $this->addSql("ALTER TABLE order_donations ADD CONSTRAINT FK_716EF29AAE51FB5F FOREIGN KEY (orderId_id) REFERENCES orders (id)");
        $this->addSql("ALTER TABLE product_to_department ADD CONSTRAINT FK_30C31F054584665A FOREIGN KEY (product_id) REFERENCES products (id)");
        $this->addSql("ALTER TABLE product_to_department ADD CONSTRAINT FK_30C31F05AE80F5DF FOREIGN KEY (department_id) REFERENCES departments (id)");
        $this->addSql("ALTER TABLE department_descriptions ADD CONSTRAINT FK_3213CC74AE80F5DF FOREIGN KEY (department_id) REFERENCES departments (id)");
        $this->addSql("ALTER TABLE department_to_feature ADD CONSTRAINT FK_346447FAE80F5DF FOREIGN KEY (department_id) REFERENCES departments (id)");
        $this->addSql("ALTER TABLE department_to_feature ADD CONSTRAINT FK_346447FF383E752 FOREIGN KEY (product_feature_id) REFERENCES product_features (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE brand_descriptions DROP FOREIGN KEY FK_4D8F90544F5D008");
        $this->addSql("ALTER TABLE brand_descriptions DROP FOREIGN KEY FK_4D8F9056D947EBB");
        $this->addSql("ALTER TABLE brand_to_department DROP FOREIGN KEY FK_B88B579644F5D008");
        $this->addSql("ALTER TABLE brand_to_department DROP FOREIGN KEY FK_B88B5796AE80F5DF");
        $this->addSql("ALTER TABLE bugs DROP FOREIGN KEY FK_1E197C9B5CBBC0F");
        $this->addSql("ALTER TABLE bugs DROP FOREIGN KEY FK_1E197C9E315F242");
        $this->addSql("ALTER TABLE contact_addresses DROP FOREIGN KEY FK_13B566DE7A1254A");
        $this->addSql("ALTER TABLE contact_addresses DROP FOREIGN KEY FK_13B566D5BE4435");
        $this->addSql("ALTER TABLE contact_addresses DROP FOREIGN KEY FK_13B566D1D8E2517");
        $this->addSql("ALTER TABLE contact_email_addresses DROP FOREIGN KEY FK_FBD6D503E7A1254A");
        $this->addSql("ALTER TABLE contact_email_addresses DROP FOREIGN KEY FK_FBD6D5035D408FBE");
        $this->addSql("ALTER TABLE contact_numbers DROP FOREIGN KEY FK_EDB1EB78E7A1254A");
        $this->addSql("ALTER TABLE contact_numbers DROP FOREIGN KEY FK_EDB1EB78C12336C6");
        $this->addSql("ALTER TABLE contact_web_addresses DROP FOREIGN KEY FK_90FEF745E7A1254A");
        $this->addSql("ALTER TABLE contact_web_addresses DROP FOREIGN KEY FK_90FEF7451E44B9BB");
        $this->addSql("ALTER TABLE contacts DROP FOREIGN KEY FK_3340157390BA1B2A");
        $this->addSql("ALTER TABLE department_descriptions DROP FOREIGN KEY FK_3213CC74AE80F5DF");
        $this->addSql("ALTER TABLE department_to_feature DROP FOREIGN KEY FK_346447FAE80F5DF");
        $this->addSql("ALTER TABLE department_to_feature DROP FOREIGN KEY FK_346447FF383E752");
        $this->addSql("ALTER TABLE departments DROP FOREIGN KEY FK_16AEB8D4727ACA70");
        $this->addSql("ALTER TABLE guarantees DROP FOREIGN KEY FK_935E0475668279F0");
        $this->addSql("ALTER TABLE guarantees DROP FOREIGN KEY FK_935E0475E2EAD863");
        $this->addSql("ALTER TABLE order_discounts DROP FOREIGN KEY FK_40D079408D9F6D38");
        $this->addSql("ALTER TABLE order_donations DROP FOREIGN KEY FK_716EF29AAE51FB5F");
        $this->addSql("ALTER TABLE order_notes DROP FOREIGN KEY FK_8285D2718D9F6D38");
        $this->addSql("ALTER TABLE order_products DROP FOREIGN KEY FK_5242B8EB8D9F6D38");
        $this->addSql("ALTER TABLE order_products DROP FOREIGN KEY FK_5242B8EB4584665A");
        $this->addSql("DROP INDEX IDX_5242B8EB4584665A ON order_products");
        $this->addSql("ALTER TABLE order_products ADD product VARCHAR(255) NOT NULL, ADD url VARCHAR(255) NOT NULL, ADD header VARCHAR(255) NOT NULL, ADD product_code VARCHAR(255) NOT NULL, ADD brand VARCHAR(255) NOT NULL, ADD short_description VARCHAR(255) NOT NULL, ADD quantity INT NOT NULL, ADD unit_cost NUMERIC(12, 4) NOT NULL, ADD recommended_retail_price NUMERIC(12, 4) NOT NULL, ADD discount NUMERIC(12, 4) NOT NULL, ADD savings NUMERIC(12, 4) NOT NULL, CHANGE product_id productId_id INT DEFAULT NULL");
        $this->addSql("CREATE INDEX IDX_5242B8EB6E48E3E9 ON order_products (productId_id)");
        $this->addSql("ALTER TABLE product_descriptions DROP INDEX UNIQ_44CA8CDD4584665A, ADD INDEX FK_44CA8CDD4584665A (product_id)");
        $this->addSql("ALTER TABLE product_descriptions DROP FOREIGN KEY FK_44CA8CDD4584665A");
        $this->addSql("ALTER TABLE product_features DROP FOREIGN KEY FK_7470B6849351284");
        $this->addSql("ALTER TABLE product_links DROP FOREIGN KEY FK_70DEDA444584665A");
        $this->addSql("ALTER TABLE product_links DROP FOREIGN KEY FK_70DEDA44D240BD1D");
        $this->addSql("ALTER TABLE product_options DROP FOREIGN KEY FK_1ECE137ECA8AD7E");
        $this->addSql("ALTER TABLE product_prices DROP FOREIGN KEY FK_86B72CFD4584665A");
        $this->addSql("ALTER TABLE product_to_department DROP FOREIGN KEY FK_30C31F054584665A");
        $this->addSql("ALTER TABLE product_to_department DROP FOREIGN KEY FK_30C31F05AE80F5DF");
        $this->addSql("ALTER TABLE product_to_feature DROP FOREIGN KEY FK_22817B84584665A");
        $this->addSql("ALTER TABLE product_to_feature DROP FOREIGN KEY FK_22817B8F383E752");
        $this->addSql("ALTER TABLE product_to_option DROP FOREIGN KEY FK_12F4BAA04584665A");
        $this->addSql("ALTER TABLE product_to_option DROP FOREIGN KEY FK_12F4BAA0C964ABE2");
        $this->addSql("ALTER TABLE products DROP FOREIGN KEY FK_B3BA5A5A44F5D008");
    }
}
