services:
  kac_admin.form.new_product:
    class: KAC\AdminBundle\Form\NewProductType
    tags:
      - { name: form.type, alias: admin_new_product }

  kac_admin.form.flow.new_product:
    class: KAC\AdminBundle\Form\NewProductFlow
    parent: craue.form.flow
    scope: request
    calls:
      - [ setFormType, [@kac_admin.form.new_product]]