services:
    kac_user.registration.form.type:
        class: KAC\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: kac_user_registration }
    kac_user.user_manager.default:
        class: KAC\UserBundle\Entity\UserManager
        arguments: [@security.encoder_factory, @fos_user.util.username_canonicalizer, @fos_user.util.email_canonicalizer, @doctrine.orm.entity_manager, %fos_user.model.user.class%]
    kac_user.registration_completed:
        class: KAC\UserBundle\EventListener\RegistrationCompletedListener
        arguments: [@session]
        tags:
            - { name: kernel.event_subscriber }