imports:
    - { resource: parameters.ini }
    - { resource: security.yml }
    - { resource: settings.php }
    
parameters:
    test:    "Yehaaa mother fucker!"

framework:
    #esi:             ~
    #translator:      { fallback: en }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    
    templating:      
        engines: ['twig']
        packages:
            cdn:
                base_urls:
                    http: [http://cdn.kitchen-appliance-centre.co.uk]
                    ssl: [https://shop.kitchenappliancecentre.co.uk]
            nocdn:
                base_urls:
                    http: [http://shop.kitchenappliancecentre.co.uk]
                    ssl: [https://shop.kitchenappliancecentre.co.uk]
        assets_base_urls:
            http: [http://cdn.kitchen-appliance-centre.co.uk]
            ssl: [https://shop.kitchenappliancecentre.co.uk]
    session:
        default_locale: %locale%
        lifetime:       31536000
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport:     smtp
    username:      sales@ridedirect.co.uk
    password:      madelaine12
    host:          mail.ridedirect.co.uk
    port:          587
    encryption:    tls

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false
