security:
    encoders:
        WebIllumination\AdminBundle\Entity\User:
            algorithm: sha512
            iterations: 100
            encode_as_base64: true

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        admin:
            entity: { class: WebIllumination\AdminBundle\Entity\User, property: emailAddress }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        admin_invoice:
           pattern:  ^/admin/orders/viewInvoice
           anonymous: ~
        
        admin_invoices:
           pattern:  ^/admin/orders/viewInvoices
           anonymous: ~
        
        admin_copy_invoice:
           pattern:  ^/admin/orders/viewCopyInvoice
           anonymous: ~
        
        admin_delivery_note:
           pattern:  ^/admin/orders/viewDeliveryNote
           anonymous: ~
        
        admin_login:
            pattern:  ^/admin/security/login
            anonymous: ~

        admin:
            pattern:    ^/admin/
            form_login:
                default_target_path: /admin
                check_path: /admin/security/login_check
                login_path: /admin/security/login
            logout:
                path:   /admin/security/logout
                target: /admin/security/login

    access_control:
        - { path: ^/admin/orders/viewInvoice/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/orders/viewInvoices/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/orders/viewCopyInvoice/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/orders/viewDeliveryNote/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/orders/viewDeliveryNotes/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/orders/viewInvoiceAndDeliveryNote/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/orders/viewInvoicesAndDeliveryNotes/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/security/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/.*, roles: ROLE_ADMIN, requires_channel: https }
        - { path: ^/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
